name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2 
    - name: Lint Ansible Playbook
      uses: ansible/ansible-lint-action@master
      with:
        targets: |
          ansible/docker_netwrok.yml
          ansible/docker_network_test.yml
          ansible/docker_swarm.yml

  execute: 
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get remove ansible
          pip install ansible==4.2
          echo "${HOME}/.local/bin" >> $GITHUB_PATH
      - name: Run docker network test
        run: "ansible-playbook -i ansible/localhost.ini ansible/docker_network_test.yml"
